# Generated by Django 2.1.1 on 2018-09-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interested',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='interested',
            name='psychiatrist',
        ),
        migrations.AddField(
            model_name='interested',
            name='interested_in',
            field=models.CharField(choices=[('evaluation', 'Evaluation'), ('psychiatrist', 'Psychiatrist')], default='evaluation', max_length=20),
        ),
    ]
